/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ChiTietPhieuNhapDAO;
import DTO.ChiTietPhieuNhap;
import DTO.PhieuNhap;
import Main.FontOptionPane;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Quang
 */
public class NhapHangJFrame extends javax.swing.JFrame {
    
    private ArrayList<ChiTietPhieuNhap> listCTPN;
    private NhapHangJPanel NhapHangJPanel;
    /**
     * Creates new form NhapHangJFrame
     */
    public NhapHangJFrame(PhieuNhap pn, NhapHangJPanel nhaphangJPanel) {
        initComponents();
        this.listCTPN = ChiTietPhieuNhapDAO.getInstance().getListCTPN(pn.getMaPN());
        setView(pn);
        LoadCTPNVaoTable(jtCTPN, jspCTPN);
        this.NhapHangJPanel = nhaphangJPanel;
        FontOptionPane.setUIFont();
    }

    public void setView(PhieuNhap pn) {
        if (pn != null) {
            jtfMaPN.setText(pn.getMaPN());
            jtfMaNCC.setText(pn.getMaNCC());
            jtfMaNV.setText(pn.getMaNV());
            jtfNgayTao.setText(pn.getNgayNhap()+ "");
            jtfTongTien.setText(pn.getTongTien() + "");
        }
    }

    void LoadCTPNVaoTable(JTable jt, JScrollPane jsp) {
        String[] header = {"Mã hàng hóa", "Tên hàng hóa", "Số lượng", "Đơn vị tính", "Giá nhập", "Thành tiên"};
        if (jt == null && jsp == null) {
            jt = jtCTPN;
            jsp = jspCTPN;
        }
        
        DefaultTableModel modelTableDb = new DefaultTableModel(header, 0) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };

        for (ChiTietPhieuNhap ctpn : listCTPN) {
            Object[] row = {ctpn.getMaHang(), ctpn.getTenHang(), ctpn.getSoLuong(), ctpn.getDVT(), ctpn.getGiaNhap(), ctpn.getThanhTien()};
            modelTableDb.addRow(row);
        }

        TableRowSorter<TableModel> rowSorter = null;

        jt.setModel(modelTableDb);
        jt.setRowSorter(rowSorter);

        jt.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
        jt.setFont(new Font("Arial", Font.PLAIN, 14));
        jt.getTableHeader().setPreferredSize(new Dimension(100, 50));
        jt.setRowHeight(50);
        jt.validate();
        jt.repaint();

        jsp.setPreferredSize(new Dimension(1350, 400));
    }
    public ArrayList<ChiTietPhieuNhap> getDataFromJTable() {
        ArrayList<ChiTietPhieuNhap> data = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) jtCTPN.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            ChiTietPhieuNhap ctpn = new ChiTietPhieuNhap();
            ctpn.setMaHang((String) model.getValueAt(i, 0));
            ctpn.setTenHang((String) model.getValueAt(i, 1));
            ctpn.setSoLuong((double) model.getValueAt(i, 2));
            ctpn.setDVT((String) model.getValueAt(i, 3));
            ctpn.setGiaNhap((double) model.getValueAt(i, 4));
            ctpn.setThanhTien((double) model.getValueAt(i, 5));
            data.add(ctpn);
        }
        return data;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnThongTinCTPN = new javax.swing.JPanel();
        jspCTPN = new javax.swing.JScrollPane();
        jtCTPN = new javax.swing.JTable();
        jlbMaPN = new javax.swing.JLabel();
        jtfMaPN = new javax.swing.JTextField();
        jlbMaNCC = new javax.swing.JLabel();
        jlbMaNV = new javax.swing.JLabel();
        jtfMaNCC = new javax.swing.JTextField();
        jlbNgayTao = new javax.swing.JLabel();
        jtfNgayTao = new javax.swing.JTextField();
        jtfMaNV = new javax.swing.JTextField();
        jlbTongTien = new javax.swing.JLabel();
        jtfTongTien = new javax.swing.JTextField();
        btn_NhapLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnThongTinCTPN.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết phiếu nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jpnThongTinCTPN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtCTPN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspCTPN.setViewportView(jtCTPN);

        jlbMaPN.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbMaPN.setText("Mã phiếu nhập");

        jtfMaPN.setEditable(false);
        jtfMaPN.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfMaPN.setDisabledTextColor(new java.awt.Color(153, 153, 153));

        jlbMaNCC.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbMaNCC.setText("Mã nhà cung cấp");

        jlbMaNV.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbMaNV.setText("Mã nhân viên");

        jtfMaNCC.setEditable(false);
        jtfMaNCC.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlbNgayTao.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbNgayTao.setText("Ngày nhập");

        jtfNgayTao.setEditable(false);
        jtfNgayTao.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jtfMaNV.setEditable(false);
        jtfMaNV.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlbTongTien.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbTongTien.setText("Tổng tiền");

        jtfTongTien.setEditable(false);
        jtfTongTien.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        btn_NhapLai.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_NhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-receipt.png"))); // NOI18N
        btn_NhapLai.setText("Nhập Lại");
        btn_NhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NhapLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnThongTinCTPNLayout = new javax.swing.GroupLayout(jpnThongTinCTPN);
        jpnThongTinCTPN.setLayout(jpnThongTinCTPNLayout);
        jpnThongTinCTPNLayout.setHorizontalGroup(
            jpnThongTinCTPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinCTPNLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jpnThongTinCTPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnThongTinCTPNLayout.createSequentialGroup()
                        .addGroup(jpnThongTinCTPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbMaNCC)
                            .addComponent(jlbMaPN)
                            .addComponent(jlbMaNV))
                        .addGap(50, 50, 50)
                        .addGroup(jpnThongTinCTPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(jtfMaNCC)
                            .addComponent(jtfMaPN))
                        .addGap(50, 50, 50)
                        .addGroup(jpnThongTinCTPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpnThongTinCTPNLayout.createSequentialGroup()
                                .addComponent(jlbNgayTao)
                                .addGap(77, 77, 77)
                                .addComponent(jtfNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnThongTinCTPNLayout.createSequentialGroup()
                                .addComponent(jlbTongTien)
                                .addGap(77, 77, 77)
                                .addGroup(jpnThongTinCTPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThongTinCTPNLayout.createSequentialGroup()
                                        .addComponent(btn_NhapLai, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22))))))
                    .addComponent(jspCTPN, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(50, 50, 50))
        );
        jpnThongTinCTPNLayout.setVerticalGroup(
            jpnThongTinCTPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinCTPNLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jpnThongTinCTPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbMaPN)
                    .addComponent(jtfNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbNgayTao))
                .addGap(18, 18, 18)
                .addGroup(jpnThongTinCTPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnThongTinCTPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlbTongTien))
                    .addGroup(jpnThongTinCTPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlbMaNCC)
                        .addComponent(jtfMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jpnThongTinCTPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMaNV)
                    .addComponent(jtfMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_NhapLai, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jspCTPN, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnThongTinCTPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnThongTinCTPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NhapLaiActionPerformed
        // TODO add your handling code here:
        ArrayList<ChiTietPhieuNhap> listCTPN = getDataFromJTable();
        String MaNCC = jtfMaNCC.getText();
        NhapHangJPanel.receiveDataFromNhapHangJFrame(listCTPN,MaNCC);
    }//GEN-LAST:event_btn_NhapLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_NhapLai;
    private javax.swing.JLabel jlbMaNCC;
    private javax.swing.JLabel jlbMaNV;
    private javax.swing.JLabel jlbMaPN;
    private javax.swing.JLabel jlbNgayTao;
    private javax.swing.JLabel jlbTongTien;
    private javax.swing.JPanel jpnThongTinCTPN;
    private javax.swing.JScrollPane jspCTPN;
    private javax.swing.JTable jtCTPN;
    private javax.swing.JTextField jtfMaNCC;
    private javax.swing.JTextField jtfMaNV;
    private javax.swing.JTextField jtfMaPN;
    private javax.swing.JTextField jtfNgayTao;
    private javax.swing.JTextField jtfTongTien;
    // End of variables declaration//GEN-END:variables
}
