CREATE DATABASE CHNONGSAN
GO

USE CHNONGSAN
GO

CREATE TABLE NhomHang (
    MaNhomHang INT IDENTITY PRIMARY KEY,
    TenNhomHang NVARCHAR(50) NOT NULL UNIQUE,
	TrangThai BIT DEFAULT 1
)

INSERT INTO NhomHang(TenNhomHang) VALUES (N'Trái cây');

CREATE TABLE NhaCungCap
(
	MaNCC INT IDENTITY PRIMARY KEY,
    TenNCC NVARCHAR(50) NOT NULL UNIQUE,
    SDT VARCHAR(11) DEFAULT N'Chưa xác định',
    DiaChi NVARCHAR(50) DEFAULT N'Chưa xác định',
	TrangThai BIT DEFAULT 1
)

INSERT INTO NhaCungCap(TenNCC, SDT, DiaChi) VALUES ('Fruit Anna', '092345678', 'TP.HCM')

CREATE TABLE HangHoa 
(
    MaHang INT IDENTITY PRIMARY KEY,
    MaNhomHang INT NOT NULL,
	MaNCC INT NOT NULL,
    TenHang NVARCHAR(50) NOT NULL UNIQUE,
    DVT NVARCHAR(20) DEFAULT N'Chưa xác định', 
    GiaBan FLOAT NOT NULL,
	HeSo FLOAT DEFAULT 1.2,
    GiaNhap FLOAT NOT NULL,
    HinhAnh VARCHAR(50) DEFAULT N'Chưa xác định',
    SoLuongTon INT DEFAULT 0,
	TrangThai BIT DEFAULT 1,
    CONSTRAINT FK_HangHoa_NhomHang FOREIGN KEY (MaNhomHang) REFERENCES NhomHang(MaNhomHang),
	CONSTRAINT FK_HangHoa_NhaCungCap FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)
)

INSERT INTO HangHoa (MaNhomHang, MaNCC, TenHang, DVT, GiaBan, GiaNhap, HinhAnh, SoLuongTon)
VALUES
(1, 1, N'Chuối', 'Kg', 10000, 80000, 'chuoi.jpg', 10);

CREATE TABLE NhanVien
(
    MaNV INT IDENTITY PRIMARY KEY,
    TenNV NVARCHAR(50) NOT NULL,
    SDT VARCHAR(11) DEFAULT N'Chưa xác định',
    UserName VARCHAR(30) NOT NULL UNIQUE,
    Password VARCHAR(30) NOT NULL,
    ChucVu NVARCHAR(50) DEFAULT N'Nhân viên',
	DiaChi NVARCHAR(50) DEFAULT N'Chưa xác định',
	TrangThai BIT DEFAULT 1
)

CREATE TABLE KhachHang
(
    MaKH INT IDENTITY PRIMARY KEY,
    TenKH NVARCHAR(50) NOT NULL,
    SDT varchar(11) DEFAULT N'Chưa xác định',
	DiaChi nvarchar(50) DEFAULT N'Chưa xác định',
	TrangThai BIT DEFAULT 1
)

CREATE TABLE HoaDon
(
    MaHD INT IDENTITY PRIMARY KEY,
    MaNV INT NOT NULL,
    MaKH INT,
    NgayTao DATETIME DEFAULT GETDATE(),
    TongTien FLOAT NOT NULL,
	TrangThai NVARCHAR(50) DEFAULT N'Đang xử lý',
    CONSTRAINT FK_HoaDon_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
    CONSTRAINT FK_HoaDon_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang (MaKH)
)

CREATE TABLE ChiTietHoaDon
(
    MaHang INT NOT NULL,
    MaHD INT NOT NULL,
    SoLuong INT DEFAULT 1,
    ThanhTien FLOAT NOT NULL,
    CONSTRAINT PK_ChiTietHoaDon primary key (MaHang, MaHD),
    CONSTRAINT FK_ChiTietHoaDon_mahang FOREIGN KEY (MaHang) REFERENCES HangHoa(MaHang),
    CONSTRAINT FK_ChiTietHoaDon_HoaDon FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD)
)

CREATE TABLE PhieuNhap
(
    MaPN INT IDENTITY PRIMARY KEY,
    MaNV INT NOT NULL,
    MaNCC INT NOT NULL,
    NgayNhap DATETIME DEFAULT GETDATE(),
    TongTien FLOAT NOT NULL,
	TrangThai NVARCHAR(50) DEFAULT N'Đang xử lý',
    CONSTRAINT FK_PhieuNhap_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien (MaNV),
    CONSTRAINT FK_PhieuNhap_NhaCungCap FOREIGN KEY (MaNCC) REFERENCES NhaCungCap (MaNCC) 
)

CREATE TABLE ChiTietPhieuNhap
(
    MaPN INT NOT NULL,
    MaHang INT NOT NULL,
    GiaNhap INT NOT NULL,
    SoLuong INT DEFAULT 5,
    ThanhTien INT NOT NULL,
    CONSTRAINT PK_ChiTietPhieuNhap primary key (MaPN, MaHang),
    CONSTRAINT FK_ChiTietPhieuNhap_MaHang FOREIGN KEY (MaHang) REFERENCES HangHoa (MaHang),
    CONSTRAINT FK_ChiTietPhieuNhap_phieunhap FOREIGN KEY (MaPN) REFERENCES PhieuNhap (MaPN) 
)